### ISSUE TITLE
iOS 13 and Linphone for background call support.

### ISSUE THREAD

**Issue by tjramoliya** [BelledonneCommunications/linphone-iphone#612]
Has an updated library been released to handle the push notification problems introduced in iOS 13? I see that one was supposed to be ready in December but I don’t see an announcement about that version going out.

**Comment by chetan1406** [comment]
facing same issue.

**Comment by Viish** [comment]
Not yet but we are close.

**Comment by chetan1406** [comment]
@Viish Thanks for replaying please update when development was done.

**Comment by victorbarskov** [comment]
@chetan1406 hey, what is your problem please describe in details. I did manage to tune the incoming calls for a current lib working with iOS 13 voip push flow. Shortly - you get your push and show the CallKit, then you use CallKit's functional and wait for a call to be initialised in the core. Once it is there you configure the audio and then fulfil the answer.

**Comment by Daniele-Tentoni** [comment]
@Viish could you give us an eta for this issue to be fixed?
@victorbarskov can you give more information or a snippet?
Thank you all.

**Comment by Viish** [comment]
If you are a client from belledonne comunications you will receive a newsletter when it will be ready.
If you are using our product under the GPL license you'll have the news when we update our app on the store.
ETA is end of the month.

**Comment by chetan1406** [comment]
@victorbarskov hello getting incoming call in background state and kill state but but in core function got null value in current call (CallManager.instance().lc?.currentCall)

**Comment by victorbarskov** [comment]
Hello everyone! Below I will explain how we did it

First of all in iOS 13 you should show call kit immediately after you got voip push

so you get your voip in didReceiveIncomingPushWithPayload and you need to show the call kit immediately - see below:

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {

   ProviderDelegate *providerDelegate = [ProviderDelegate instance];
   [providerDelegate reportIncomingCall:uuid phoneNumber: phoneNumber video:NO];

} 
Then your incoming call is handled by ProviderDelegate - so if user make answer action we do like this 

- (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action {
            
    if ([LinphoneCallManager currentCall]) {
        self.callKitCalls++;
        [self configAudioSession:[AVAudioSession sharedInstance]];
        [action fulfill];
        LinphoneCall *call = [LinphoneCallManager currentCall];
        if (call != NULL) {
            self.pendingCall = call;
            return;
        };
    } else {
        self.answerCallAction = action;
        self.callConnectionTimer = [NSTimer timerWithTimeInterval:1.0 target:self selector:@selector(callConnectHandler) userInfo:nil repeats:YES];
        self.callConnectCounter = 20.0;
        [[NSRunLoop mainRunLoop] addTimer:self.callConnectionTimer forMode:NSRunLoopCommonModes];
    }   
}


so in callConnect handler you are waiting for your call if nothing yet initialised in LP core 

-(void)callConnectHandler {
        
    double connectCounter = self.callConnectCounter;
    BOOL shouldCount = connectCounter > 0;
    
    if (shouldCount) {
        self.callConnectCounter = MAX(connectCounter - 1, 0);
        if ([LinphoneCallManager currentCall]) {
            LinphoneCall *call = [LinphoneCallManager currentCall];
            self.callKitCalls++;
            if (call != NULL) {
                if (self.answerCallAction) {
                    self.pendingCall = call;
                    [self configAudioSession:[AVAudioSession sharedInstance]];
                    [self.answerCallAction fulfill];
                }
                [self invalidateTimer:self.callConnectionTimer];
                return;
            };
        }
    } else {
        [self invalidateTimer:self.callConnectionTimer];
        if ([LinphoneCallManager currentCall]) {
            [LinphoneCallManager terminateCurrentCall];
            if (linphone_core_get_calls_nb(LC) > 1) {
                linphone_core_terminate_all_calls(LC);
            }
            [self terminateAllCallKitCalls];
        } else {
            [self terminateAllCallKitCalls];
        }
    }
}

This one is worth attention 

                    [self configAudioSession:[AVAudioSession sharedInstance]];
                    [self.answerCallAction fulfill];

You got the audio session, you got the self.pending call and you answer that pending call in 

- (void)provider:(CXProvider *)provider didActivateAudioSession:(AVAudioSession *)audioSession;

ALSO IS VERY IMPORTANT THAT WE MAKE REGISTRATION BY THE ACTON OF INCOMING CALL - SO ONCE VOIP COME WE DO OUR REGISTRATION

**Comment by pasha4uu** [comment]
> Hello everyone! Below I will explain how we did it
> 
> First of all in iOS 13 you should show call kit immediately after you got voip push
> 
> so you get your voip in didReceiveIncomingPushWithPayload and you need to show the call kit immediately - see below:
> 
> * (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
>   ProviderDelegate *providerDelegate = [ProviderDelegate instance];
>   [providerDelegate reportIncomingCall:uuid phoneNumber: phoneNumber video:NO];
> 
> }
> Then your incoming call is handled by ProviderDelegate - so if user make answer action we do like this
> 
> * (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action {
>   if ([LinphoneCallManager currentCall]) {
>   self.callKitCalls++;
>   [self configAudioSession:[AVAudioSession sharedInstance]];
>   [action fulfill];
>   LinphoneCall *call = [LinphoneCallManager currentCall];
>   if (call != NULL) {
>   self.pendingCall = call;
>   return;
>   };
>   } else {
>   self.answerCallAction = action;
>   self.callConnectionTimer = [NSTimer timerWithTimeInterval:1.0 target:self selector:@selector(callConnectHandler) userInfo:nil repeats:YES];
>   self.callConnectCounter = 20.0;
>   [[NSRunLoop mainRunLoop] addTimer:self.callConnectionTimer forMode:NSRunLoopCommonModes];
>   }
>   }
> 
> so in callConnect handler you are waiting for your call if nothing yet initialised in LP core
> 
> -(void)callConnectHandler {
> 
> ```
> double connectCounter = self.callConnectCounter;
> BOOL shouldCount = connectCounter > 0;
> 
> if (shouldCount) {
>     self.callConnectCounter = MAX(connectCounter - 1, 0);
>     if ([LinphoneCallManager currentCall]) {
>         LinphoneCall *call = [LinphoneCallManager currentCall];
>         self.callKitCalls++;
>         if (call != NULL) {
>             if (self.answerCallAction) {
>                 self.pendingCall = call;
>                 [self configAudioSession:[AVAudioSession sharedInstance]];
>                 [self.answerCallAction fulfill];
>             }
>             [self invalidateTimer:self.callConnectionTimer];
>             return;
>         };
>     }
> } else {
>     [self invalidateTimer:self.callConnectionTimer];
>     if ([LinphoneCallManager currentCall]) {
>         [LinphoneCallManager terminateCurrentCall];
>         if (linphone_core_get_calls_nb(LC) > 1) {
>             linphone_core_terminate_all_calls(LC);
>         }
>         [self terminateAllCallKitCalls];
>     } else {
>         [self terminateAllCallKitCalls];
>     }
> }
> ```
> 
> }
> 
> This one is worth attention
> 
> ```
>                 [self configAudioSession:[AVAudioSession sharedInstance]];
>                 [self.answerCallAction fulfill];
> ```
> 
> You got the audio session, you got the self.pending call and you answer that pending call in
> 
> * (void)provider:(CXProvider *)provider didActivateAudioSession:(AVAudioSession *)audioSession;
> 
> ALSO IS VERY IMPORTANT THAT WE MAKE REGISTRATION BY THE ACTON OF INCOMING CALL - SO ONCE VOIP COME WE DO OUR REGISTRATION

hi ,

[providerDelegate reportIncomingCall:uuid phoneNumber: phoneNumber video:NO];

this method  is not there in providerDELEGATE ?
I have this method only... how 
[provider reportIncomingCall:callfm withUUID:self.uuid handle:callf6m video:NO];

**Comment by pasha4uu** [comment]
I Implemented for code  for when app in kill state. below code is working some times and some times not working .. please help me.. any mistake in the code ? and or any implementation  backend server for full working without drop calls?

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
    
    NSLog(@"pushPayloadd ---->>> %@",payload.dictionaryPayload);
    
    // Hard coaded refersh linphone registration
//    LinphoneProxyConfig *proxyCfg = linphone_core_get_default_proxy_config(LC);
//    linphone_proxy_config_refresh_register(proxyCfg);
    
    
 // iOS13 - VoIP - START
    CXProviderConfiguration *config = [[CXProviderConfiguration alloc]
        initWithLocalizedName:[NSBundle.mainBundle objectForInfoDictionaryKey:@"CFBundleDisplayName"]];
    config.ringtoneSound = @"notes_of_the_optimistic.caf";
    config.supportsVideo = FALSE;
    config.iconTemplateImageData = UIImagePNGRepresentation([UIImage imageNamed:@"callkit_logo"]);

    NSArray *ar = @[ [NSNumber numberWithInt:(int)CXHandleTypeGeneric] ];
    NSSet *handleTypes = [[NSSet alloc] initWithArray:ar];
    [config setSupportedHandleTypes:handleTypes];
    [config setMaximumCallGroups:2];
    [config setMaximumCallsPerCallGroup:1];
    
    self.cxProvider = [[CXProvider alloc] initWithConfiguration:config];

    NSDictionary *dict = [payload.dictionaryPayload objectForKey:@"aps"];
    NSString *callf6m= [dict objectForKey:@"callfrom"];
    if (callf6m.length==0) {
        callf6m = @"Nagaraju";
    }
    
   // if ([payload.dictionaryPayload[@"tcall_type"] isEqualToString:@"tcancel"]) {
         CXHandle *callHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:callf6m];

         CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
         callUpdate.remoteHandle = callHandle;
         callUpdate.supportsDTMF = YES;
         callUpdate.supportsHolding = YES;
         callUpdate.supportsGrouping = NO;
         callUpdate.supportsUngrouping = NO;
         callUpdate.hasVideo = NO;

         self.uuid = [NSUUID UUID];
  //  UIBackgroundTaskIdentifier  bgTaskID = [[UIApplication sharedApplication]beginBackgroundTaskWithExpirationHandler:nil] ;
         [self.cxProvider reportNewIncomingCallWithUUID:self.uuid update:callUpdate completion:^(NSError *error) {
             NSLog(@"error1 ----> %@",error);
             if (error) {
                 if (@available(iOS 13.0, *)) {
                     [self.cxProvider reportCallWithUUID:self.uuid endedAtDate:[NSDate now] reason:CXCallEndedReasonRemoteEnded];
                 } else {
                     // Fallback on earlier versions
                 }
                 
             }
         }];
//    [self.cxProvider reportCallWithUUID:self.uuid updated:callUpdate];

 //   [[UIApplication sharedApplication]endBackgroundTask:bgTaskID];
    
 
     CXCallController *callController = [[CXCallController alloc] initWithQueue:dispatch_get_main_queue()];

         dispatch_async(dispatch_get_main_queue(), ^{

             CXEndCallAction *endCallAction = [[CXEndCallAction alloc] initWithCallUUID:self.uuid];
             CXTransaction *transaction = [[CXTransaction alloc] initWithAction:endCallAction];

             [callController requestTransaction:transaction completion:^(NSError *error) {
                 NSLog(@"error2 ----> %@",error);
                 if (@available(iOS 13.0, *)) {
                     [self.cxProvider reportCallWithUUID:self.uuid endedAtDate:[NSDate now] reason:CXCallEndedReasonFailed];
                 } else {
                     // Fallback on earlier versions
                 }

             }];

         });

      //   return;
   //  }
    
     // iOS13 - VoIP - END
   
    
//    NSDictionary *payloadD = payload.dictionaryPayload;
//    NSLog(@"payloadD----->>> %@",payloadD);
//    NSDictionary *dict = [payloadD objectForKey:@"aps"];
//    NSString *callTyp = [dict objectForKey:@"callType"];
//    if ([callTyp isEqualToString:@"Incoming"]) {
//        [self processPush:payload.dictionaryPayload];
//    }
//    else{
//        NSString * number = [dict objectForKey:@"alert"];
//        [self saveMissedCallLocal:[dict objectForKey:@"phonenumber"]] ;
//        [self showLocalNotifyWithMessage:number];
//    }
    
    
    
    [self processPush:payload.dictionaryPayload];
    completion();

//    dispatch_async(dispatch_get_main_queue(), ^{completion();});
}

**Comment by rayjaynz** [comment]
Can anybody confirm if the iOS 13 SDK Call Kit push notification changes are available yet in the Linphone codebase?  I've tried to test the latest Linphone App but failing to get an activation code so I'm not sure if this has been fixed or not in the latest code base.  We have many users who can't receive incoming calls reliably on the latest iOS versions and I'm keen to find a solution.  Is the above code a manual patch on the existing code base or has it been submitted?

**Comment by Viish** [comment]
Hi,
We have published a beta on test flight with support for iOS 13.
Code is in release/4.4 branch of the SDK and release/4.3 branch of the app.

**Comment by tjramoliya** [comment]
@Viish i have try with your code. but it's required some latest swift class and linphonesw.framework, i have linphone SDK 4.1 without pod i have added all framework as manually. So can you guild me how to latest framework in my project.
I have tried but i get error that linphonesw is build in swift 5.0.1 and you are compiling swift 5.1.2.

I am not able to build application again after change so can you guild me or help me ?

**Comment by tjramoliya** [comment]
@Viish this issue is not solved then how can you close this ?

**Comment by tjramoliya** [comment]
> Hi,
> We have published a beta on test flight with support for iOS 13.
> Code is in release/4.4 branch of the SDK and release/4.3 branch of the app.

I have check that code is not able to run that code as i am getting linphonesw compilation error.

**Comment by TusharSharma651** [comment]
I am still facing this issue in 4.4.0, Has someone fixed this issue?

**Comment by ravi6880** [comment]
> Hi,
> We have published a beta on test flight with support for iOS 13.
> Code is in release/4.4 branch of the SDK and release/4.3 branch of the app.

I have used the linphone source code in my app , but the callkit is still not working

**Comment by Raviojha62** [comment]
@tjramoliya or any one got any solution. latest code say that it support to callkit , but i am not getting any notification when app is in background

**Comment by ankur1986** [comment]
> @chetan1406 hey, what is your problem please describe in details. I did manage to tune the incoming calls for a current lib working with iOS 13 voip push flow. Shortly - you get your push and show the CallKit, then you use CallKit's functional and wait for a call to be initialised in the core. Once it is there you configure the audio and then fulfil the answer.

What is "call-id" in push message? Is this "caller-id"? NSDictionary *aps = [userInfo objectForKey:@"aps"];
	//NSString *loc_key = [aps objectForKey:@"loc-key"] ?: [[aps objectForKey:@"alert"] objectForKey:@"loc-key"];
	NSString *callId = [aps objectForKey:@"call-id"] ?: @"";
